name: HealthCareAB
on: pull_request
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Start testing
        run: mvn -B package
      - name: Run test
        run: mvn test
